name: Continuous Integration

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - sp/src/**
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - sp/src/**

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    strategy:
      fail-fast: false
      matrix:
        configuration: [ Release, Debug ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Build
      run: msbuild sp\src\EZ.sln /m /nologo /p:Configuration=${{ matrix.configuration }} /v:m
    - name: Prepare artifacts
      run: |
        mkdir -vb artifacts
        mv -vb sp\src\game\client\${{ matrix.configuration }}_EZ\*.dll, sp\src\game\server\${{ matrix.configuration }}_EZ\*.dll artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.configuration }}_EZ
        path: artifacts
